// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhfbxftaburyxxjcomto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoZmJ4ZnRhYnVyeXh4amNvbXRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzc5ODAsImV4cCI6MjA2MjgxMzk4MH0.8xs5fpfzdGy8KNHxgDs25GZsuOkn8Mwov8wV-NArZUM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);